# This is based off https://docs.docker.com/compose/rails/
rails:
  build: .
  volumes:
    - .:/mnt/somerville-teacher-tool
  working_dir: /mnt/somerville-teacher-tool
  environment:
    DATABASE_URL: postgresql://postgres@postgres # overrides hostname and username
  ports:
    - "3000:3000"
  links:
    - postgres
  command: bundle exec rails s -p 3000 -b '0.0.0.0'

postgres:
  image: postgres
  ports:
    - "5432:5432"
  volumes:
    - /var/lib/postgresql/data

tools:
  image: node:6.4.0
  volumes:
    - .:/mnt/somerville-teacher-tool
  working_dir: /mnt/somerville-teacher-tool/scripts/tools
  command: npm run lint-quiet